apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
  namespace: kafka
data:
  config.yml: |-
    kafka:
      clusters:
        - name: clusters
          bootstrapServers: kafka-cluster-kafka-bootstrap:9092
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false