apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: zipkin
  namespace: istio-system
spec:
  gateways:
  - istio-system/global-gateway
  hosts:
  - zk.example.local
  http:
  - route:
    - destination:
        host: zipkin.istio-system.svc.cluster.local
        port:
          number: 9411
