apiVersion: v1
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - disableDeletion: false
      folder: istio
      name: istio
      options:
        path: /var/lib/grafana/dashboards/istio
      orgId: 1
      type: file
    - disableDeletion: false
      folder: istio
      name: istio-services
      options:
        path: /var/lib/grafana/dashboards/istio-services
      orgId: 1
      type: file
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      orgId: 1
      type: prometheus
      url: http://prometheus:9090
    - access: proxy
      editable: true
      isDefault: false
      jsonData:
        timeInterval: 5s
      name: Loki
      orgId: 1
      type: loki
      url: http://loki:3100
  grafana.ini: |
    [auth]
    oauth_allow_insecure_email_lookup=true
    [auth.generic_oauth]
    name = OAuth
    enabled = true
    allow_sign_up = true
    client_id = grafana-oauth
    client_secret = Bz1RvkrW0KyPnpADp5yLU15JuYFXazfI
    scopes = openid email profile roles
    auth_url = http://10.100.100.100:8080/realms/infra/protocol/openid-connect/auth
    token_url = http://10.100.100.100:8080/realms/infra/protocol/openid-connect/token
    api_url = http://10.100.100.100:8080/realms/infra/protocol/openid-connect/userinfo
    redirect_uri = http://grafana.example.local/login/generic_oauth
    role_attribute_path = contains(realm_access.roles[*], 'Admin') && 'Admin' || contains(realm_access.roles[*], 'Editor') && 'Editor' || 'Viewer'
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    level = debug
    filters = oauth:debug
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = grafana.example.local
    root_url = %(protocol)s://%(domain)s/
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.5.5
    helm.sh/chart: grafana-6.57.4
  name: grafana
  namespace: istio-system
