apiVersion: v1
data:
  oidc.config: |
    name: Keycloak
    issuer: http://10.100.100.100:8080/realms/infra
    clientID: argocd
    clientSecret: $argocd-secret:oidcClientSecret
    requestedIDTokenClaims:
      groups:
        essential: true
    requestedScopes:
      - openid
      - profile
      - email
  url: http://argocd.example.local
  users.anonymous.enabled: "false"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd