apiVersion: v1
data:
  admin.password: JDJhJDEwJHN6YkNzSHBZNExhS25VV1ozeHFRQnV5enVPbVlDaUpSMWNRWEljTlV1WXEvSHl6U2V1RXQy
  admin.passwordMtime: MjAyMy0xMC0xNVQxMDowMzoxMlo=
  oidcClientSecret: TlM2azFKOXR0SERZdGx3a3NFM3pZYlkyc0tQemF3Umw=
  server.secretkey: QzZxa3hMOC96TllQWUcrVzJaeVJONTQyUDNLQWJtT1JNbXdxV0xkYko0RT0=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque